# -*- coding: utf-8 -*-
"""character detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tovtqTtrqceAbIXPu5wC3SUDnZXMGwmz
"""

!pip install opencv-python-headless pytesseract

!sudo apt-get install tesseract-ocr

import cv2
import pytesseract
from google.colab.patches import cv2_imshow  # Display images in Colab

# Upload your image to Google Colab and load it
from google.colab import files
uploaded = files.upload()

# Read and display the uploaded image
image_path = list(uploaded.keys())[0]
image = cv2.imread(image_path)
cv2_imshow(image)

# Preprocessing
# You can add your preprocessing code here

# Text Detection
# You can add your text detection code here

# Text Recognition
# You can add your text recognition code here using pytesseract

# Print the detected text
text = pytesseract.image_to_string(image)
print("Detected Text:", text)